[package]
name = "enuminfo"
version = "0.1.0"
edition = "2024"

[features]
default = ["from-str"]
"from-str" = ["enuminfo_macros/from-str"]
"skip-inherent" = ["enuminfo_macros/skip-inherent"]

[dependencies]
enuminfo_macros = { git = "https://github.com/dante19031999/enuminfo-macros" , features = ["impl-enuminfo"]}